#!/bin/bash

# Script to find and comment out tor exit nodes in the blocklist.
# cd to the nginx-bad-bot-blocker directory & run with `./find-tor-exits`.

cd conf.d
wget 'https://check.torproject.org/torbulkexitlist'
mv torbulkexitlist ../tor-exits

echo "Running sed.."
while read line
do
    sed -i -e "s/^\t*$line\t*1;$/#\t$line\t\t1;/g" globalblacklist.conf
done < ../tor-exits

echo "Running grep.."
while read line
do
    grep $line globalblacklist.conf
done < ../tor-exits

rm globalblacklist.conf-e
