#!/bin/bash

repo="raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/refs/heads"
branch="master"
path="conf.d"
blocklist="globalblacklist.conf"

git checkout upstream
cd $path; rm $blocklist
wget https://$repo/$branch/$path/$blocklist
